import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SideBar from "./(shared)/containers/Sidebar";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen bg-white">
      <SideBar />
      <main>{children}</main>
    </div>
  );
}
